process METABAT2 {
    tag "$sample_id"
    label 'process_medium'

    container 'quay.io/biocontainers/metabat2:2.18--h6f16272_0'

    publishDir "${params.outdir}/04_binning/metabat2", mode: 'copy', pattern: "${sample_id}_bins"
    publishDir "${params.outdir}/04_binning/metabat2", mode: 'copy', pattern: "*.log"
    publishDir "${params.outdir}/04_binning/metabat2", mode: 'copy', pattern: "*_depth.txt"

    input:
    tuple val(sample_id), path(assembly)
    tuple val(sample_id), path(bam), path(bai)

    output:
    tuple val(sample_id), path("${sample_id}_bins/*.fa"), emit: bins, optional: true
    tuple val(sample_id), path("${sample_id}.metabat2.log"), emit: log
    tuple val(sample_id), path("${sample_id}_depth.txt"), emit: depth
    path "versions.yml", emit: versions

    when:
    task.ext.when == null || task.ext.when

    script:
    def args = task.ext.args ?: ''
    def min_contig_length = params.metabat2_min_contig ?: 2500
    def min_bin_size = params.metabat2_min_bin ?: 200000
    
    """
    echo "Starting MetaBAT2 binning for ${sample_id}" | tee ${sample_id}.metabat2.log
    echo "Assembly: ${assembly}" | tee -a ${sample_id}.metabat2.log
    echo "BAM file: ${bam}" | tee -a ${sample_id}.metabat2.log
    echo "Min contig length: ${min_contig_length}" | tee -a ${sample_id}.metabat2.log
    echo "Min bin size: ${min_bin_size}" | tee -a ${sample_id}.metabat2.log
    echo "Started: \$(date)" | tee -a ${sample_id}.metabat2.log
    
    # Create output directory
    mkdir -p ${sample_id}_bins
    
    # Decompress assembly if it's gzipped (using pigz if available, fallback to gunzip)
    if [[ ${assembly} == *.gz ]]; then
        echo "Decompressing assembly..." | tee -a ${sample_id}.metabat2.log
        if command -v pigz > /dev/null 2>&1; then
            pigz -dc ${assembly} > ${sample_id}_assembly.fasta
        else
            gunzip -c ${assembly} > ${sample_id}_assembly.fasta
        fi
        ASSEMBLY_FILE=${sample_id}_assembly.fasta
    else
        ASSEMBLY_FILE=${assembly}
    fi
    
    # Calculate depth from provided BAM file
    echo "Calculating contig depths from BAM..." | tee -a ${sample_id}.metabat2.log
    jgi_summarize_bam_contig_depths --outputDepth ${sample_id}_depth.txt ${bam} 2>&1 | tee -a ${sample_id}.metabat2.log
    
    # Run MetaBAT2 binning
    echo "Running MetaBAT2 binning..." | tee -a ${sample_id}.metabat2.log
    metabat2 \\
        -i \$ASSEMBLY_FILE \\
        -a ${sample_id}_depth.txt \\
        -o ${sample_id}_bins/${sample_id}_bin \\
        -t ${task.cpus} \\
        -m ${min_contig_length} \\
        -s ${min_bin_size} \\
        --saveCls \\
        --unbinned \\
        ${args} 2>&1 | tee -a ${sample_id}.metabat2.log
    
    echo "MetaBAT2 completed: \$(date)" | tee -a ${sample_id}.metabat2.log
    
    # Count number of bins
    BIN_COUNT=\$(ls ${sample_id}_bins/*.fa 2>/dev/null | wc -l)
    echo "Number of bins generated: \$BIN_COUNT" | tee -a ${sample_id}.metabat2.log
    
    if [ \$BIN_COUNT -eq 0 ]; then
        echo "WARNING: No bins generated by MetaBAT2 (sample may lack sufficient coverage)" | tee -a ${sample_id}.metabat2.log
    fi

    cat <<-END_VERSIONS > versions.yml
    "${task.process}":
        metabat2: \$(metabat2 --help 2>&1 | grep -o 'version [0-9.]*' | cut -d' ' -f2)
        bwa: 0.7.17
        samtools: 1.17
    END_VERSIONS
    """
}